default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST") %>
  username: postgres
  password: <%= ENV.fetch("DB_PASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: nagaoka_internship_site_development

test:
  <<: *default
  database: nagaoka_internship_site_test

staging:
  <<: *default
  database: nagaoka_internship_site_staging

production:
  <<: *default
  database: nagaoka_internship_site_production
